name: tweet_ui
description: Show Tweets from a Twitter API JSON on Android and iOS. Support for Tweets with 1-4 photos, Video, GIFs, hashtags, mentions, symbols, urls, quoted Tweets and retweets.
version: 2.5.0-nullsafety.2
author: OmniNext team @ Schibsted <michal.kawalko@schibsted.com>
homepage: https://github.com/schibsted/tweet_ui

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0-nullsafety
  intl: ^0.17.0
  video_player: ^2.0.2
  better_player: ^0.0.63
  photo_view: ^0.11.1
  url_launcher: ^6.0.2
  html_unescape: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/tw__ic_gif_badge.png
    - assets/1.5x/tw__ic_gif_badge.png
    - assets/2.0x/tw__ic_gif_badge.png
    - assets/3.0x/tw__ic_gif_badge.png
    - assets/tw__ic_logo_blue.png
    - assets/1.5x/tw__ic_logo_blue.png
    - assets/2.0x/tw__ic_logo_blue.png
    - assets/3.0x/tw__ic_logo_blue.png
    - assets/tw__ic_play_default.png
    - assets/1.5x/tw__ic_play_default.png
    - assets/2.0x/tw__ic_play_default.png
    - assets/3.0x/tw__ic_play_default.png
    - assets/tw__ic_tweet_verified.png
    - assets/1.5x/tw__ic_tweet_verified.png
    - assets/2.0x/tw__ic_tweet_verified.png
    - assets/3.0x/tw__ic_tweet_verified.png
    - assets/tw__ic_retweet_light.png
    - assets/1.5x/tw__ic_retweet_light.png
    - assets/2.0x/tw__ic_retweet_light.png
    - assets/3.0x/tw__ic_retweet_light.png
